### PR TITLE
Add and fill section development-cycle

### PR DESCRIPTION
**Pull request by nightscape**
**What kind of change does this PR introduce?**

- [x] Add a project
- [ ] Update a project
- [ ] Remove a project
- [x] Add or update a category
- [ ] Change configuration
- [ ] Documentation
- [ ] Other, please describe:

**Description:**

Build tools are usually the first touch point with a language, users should get some guidance on what exists and is popular.

**Checklist:**

- [x] I have read the [CONTRIBUTING](https://github.com/best-of-lists/best-of/blob/main/CONTRIBUTING.md) guidelines.
- [x] I have not modified the `README.md` file. Projects are only supposed to be added or updated within the `projects.yaml` file since the `README.md` file is automatically generated.

### CODE REVIEW

**Review by stkeky — COMMENTED** [review]
Hey @nightscape, thank you so much for contribution.

One note, `SBT` and `mill` are both part of `env` category, so they can't be part of another category. I'm fine with both adding the new `build-tools` category and removing them from `env` or adding the rest of the projects to the `env` category, whatever you prefer.

**Comment by nightscape** [comment]
Ah, how could I miss this 😅 
I think splitting up the rather broad `env` category makes sense.
For `build-tools` there's many adjacent tools like `scalafmt`, `bloop` and `metals` that somehow belong together with the build-tools but are not build-tools themselves.
Not sure if those should all be in the same category with the build-tools...
Maybe something like `development-cycle` ??

**Comment by stkeky** [comment]
@nightscape No worries 😄 
I like that idea of `development-cycle`, it's not too narrow and not too broad. We can have that and everything outside of it left in `env`.

**Comment by nightscape** [comment]
@stkeky ok, done 👍 
I guess it's best to squash-merge this PR.

**Review by stkeky — APPROVED** [review]
LGTM. 🎉

**Pull request merged**
